filebeat.inputs:

- type: log
  paths:
    - /var/log/services/traefik/*.log
  fields:
    service: traefik

- type: log
  paths:
    - /var/log/services/wordpress/*.log
  fields:
    service: wordpress

- type: log
  paths:
    - /var/log/services/keycloak/*.log
  fields:
    service: keycloak

- type: log
  paths:
    - /var/log/services/mariadb-wp/*.log
  fields:
    service: mariadb-wp

- type: log
  paths:
    - /var/log/services/mariadb-kc/*.log
  fields:
    service: mariadb-kc

output.logstash:
  hosts: ["192.168.5.2:5044"]
