tls:
  certificates:
    - certFile: /certs/traefik.crt
      keyFile: /certs/traefik.key
  stores:
    default:
      defaultCertificate:
        certFile: /certs/traefik.crt
        keyFile: /certs/traefik.key
